statics/__init__.py
# -*- coding: utf-8 -*-
"""
    statics
    ~~~~~~~~~~~~~~

    Statics application package
"""
from functools import wraps


def route(bp, *args, **kwargs):
    """Route decorator for use in blueprints"""
    def decorator(f):
        @bp.route(*args, **kwargs)
        @wraps(f)
        def wrapper(*args, **kwargs):
            return f(*args, **kwargs)
        return f

    return decorator

statics/views.py
# -*- coding: utf-8 -*-
"""
    statics.views
    ~~~~~~~~~~~~~~

    Views module that contains the 'views' blueprint that handles
    all basic endpoints
"""
from flask import current_app, Blueprint, render_template

from . import route
from .extensions import flatpages


bp = Blueprint('views', __name__)

@route(bp, '/')
def index():
    """On the index page, show a list of blog posts"""
    posts = [p for p in flatpages if p.path.startswith(current_app.config['POST_DIR'])]
    return render_template('index.html', posts=posts)

@route(bp, '/pages/<name>/')
def page(name):
    """For non-blogpost pages, e.g. About, Contact, etc..."""
    path = '{}/{}'.format(current_app.config['PAGE_DIR'], name)
    page = flatpages.get_or_404(path)
    return render_template('page.html', page=page)

@route(bp, '/posts/<name>/')
def post(name):
    """For blogpost type pages"""
    path = '{}/{}'.format(current_app.config['POST_DIR'], name)
    post = flatpages.get_or_404(path)
    return render_template('post.html', post=post)

statics/templates/index.html
{% extends 'layouts/base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
  <div class="entries">
  {% for post in posts %}
    <div class="entry-list-item">
      <div class="date">{{ post.date }}</div>
      <div class="detail">
        <h1 class="entry-list-title">
          <a href="{{ url_for('views.post', name=post.path.replace('posts/', '')) }}">
            {{ post.title }}
          </a>
        </h1>
        <div class="summary">
          <p>{{ post.summary }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
{% endblock content %}

statics/templates/layouts/_footer.html
<div id="footer">
    <div class="container">
    Cool Beans
    </div>
</div>

statics/templates/layouts/base.html
{% extends 'layouts/skeleton.html' %}

{% block navbar %}
{% include 'layouts/_navbar.html' %}
{%- endblock navbar %}

{% block footer %}
{% include 'layouts/_footer.html' %}
{% endblock footer%}

statics/templates/layouts/skeleton.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" media="screen">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css">
    {%- endblock styles %}
    {%- block header_scripts %}
    {%- if not config['DEBUG'] %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      // ga('create', 'YOUR-UA-CODE', 'DOMAIN.COM');
      // ga('send', 'pageview');
    </script>
    {%- endif %}
    {%- endblock header_scripts %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    <div id="wrap">
        {% block navbar %}
        {%- endblock navbar %}
        <div class="content">
        {% block content -%}
        {%- endblock content %}
        </div>
    </div>
    {% block footer -%}
    {%- endblock footer %}
    {% block scripts %}
    <script src="//code.jquery.com/jquery.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.min.js') }}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

statics/templates/page.html
{% extends 'layouts/base.html' %}
{% block title %}{{ page.title }}{% endblock title %}
{% block content %}
  <h1 class="title">{{ page.title }}</h1>
  {{ page.html|safe }}
{% endblock content %}

statics/templates/post.html
{% extends 'layouts/base.html' %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
  <h1 class="title">{{ post.title }}</h1>
  <p id="post_date" class="date">
    written on {{ post.date }}
  </p>
  {{ post.html|safe }}
  {% if post.tags %}
    <p class="tags">Tags:
      {% for tag in post.tags %}
        {{ tag }}
      {% endfor %}
    </p>
  {% endif %}
{% endblock content %}